import sys
import os
import shutil

# This template should be the same as in the pyproject.toml file for the esl_studio package
VERSION_FILE_TEMPLATE = """\
# ESL-Studio version file - _version.py
# Generated by setuptools-scm
# Don't change, don't track in version control

# from standard template for the __ vars
__all__ = [
    "__version__",
    "__version_tuple__",
    "__commit_id__",
    "version",
]

TYPE_CHECKING = False
if TYPE_CHECKING:
    from typing import Tuple
    from typing import Union

    VERSION_TUPLE = Tuple[Union[int, str], ...]
    COMMIT_ID = Union[str, None]
else:
    VERSION_TUPLE = object
    COMMIT_ID = object

__version__: str
__version_tuple__: VERSION_TUPLE
__commit_id__: COMMIT_ID

__version__ = {version!r}
__version_tuple__ = version_tuple = {version_tuple!r}
__commit_id__ = {scm_version.short_node!r}

# for 'version' and extra: 'build_time'
version:str
build_time:str

version = {version!r}
build_time = '{scm_version.time.year}-{scm_version.time.month:02}-{scm_version.time.day:02} {scm_version.time.hour:02}:{scm_version.time.minute:02}'\

"""
VERSION_FILE_INFO_TEMPLATE = """\
# UTF-8
#
# For more details about fixed file info 'ffi' see:
# http://msdn.microsoft.com/en-us/library/ms646997.aspx
VSVersionInfo(
  ffi=FixedFileInfo(
    # filevers and prodvers should be always a tuple with four items: (1, 2, 3, 4)
    # Set not needed items to zero 0.
    filevers=({ver1}, {ver2}, {ver3}, {ver4}),
    prodvers=({ver1}, {ver2}, {ver3}, {ver4}),
    # Contains a bitmask that specifies the valid bits 'flags'r
    mask=0x0,
    # Contains a bitmask that specifies the Boolean attributes of the file.
    flags=0x0,
    # The operating system for which this file was designed.
    # 0x4 - NT and there is no need to change it.
    OS=0x0,
    # The general type of file.
    # 0x1 - the file is an application.
    fileType=0x0,
    # The function of the file.
    # 0x0 - the function is not defined for this fileType
    subtype=0x0,
    # Creation date and time stamp.
    date=(0, 0)
    ),
  kids=[
    StringFileInfo(
      [
      StringTable(
        u'080904b0',
        [StringStruct(u'FileDescription', u'{app_name} - {app_descr}'),
        StringStruct(u'FileVersion', u'{ver1}, {ver2}, {ver3}, {ver4}'),
        StringStruct(u'InternalName', u'esl_studio'),
        StringStruct(u'LegalCopyright', u'{app_copyright}'),
        StringStruct(u'LegalTrademarks', u'\\0'),
        StringStruct(u'OriginalFilename', u'esl_studio.exe'),
        StringStruct(u'ProductName', u'{app_name}'),
        StringStruct(u'ProductVersion', u'{ver1}, {ver2}, {ver3}, {ver4}')])
      ]),
    VarFileInfo([VarStruct(u'Translation', [2057, 1200])])
  ]
)
"""

def update_esl_studio_version_file():
    retcode = 0
    err_str = ""
    from setuptools_scm import get_version as get_scm_version
    got_git = shutil.which("git")
    if got_git is not None:
        this_module_dir = os.path.dirname(os.path.realpath(__file__)) # in the project's scripts directory
        project_dir = os.path.join(this_module_dir, os.pardir)
        a_project_file=os.path.realpath(os.path.join(project_dir, "pyproject.toml"))
        version_file = os.path.join('src', 'esl_studio', '_version.py') # relative to the a_project_file's directory
        scm_version = ""
        try:
            scm_version = get_scm_version(relative_to=a_project_file,
                                          version_scheme="post-release",
                                          local_scheme="no-local-version",
                                          fallback_version="0.0.0.0+unknown",
                                          version_file=version_file,
                                          version_file_template=VERSION_FILE_TEMPLATE,
                                          )
        except Exception: pass
        if not scm_version:
            err_str = "\nCould not determine version - version file not updated\n"
            retcode = 1
    else:
        err_str = "\nCould not find \"git\" command - version file not updated\n"
        retcode = 99
    return retcode, err_str

def set_esl_studio_file_version_info():
    retcode = 0
    err_str = ""
    import esl_studio.app.general as general
    app_name = general.APP_NAME
    app_version = general.APPLICATION_VERSION_STRING
    app_copyright = general.APP_COPYRIGHT
    app_descr = general.APP_DESCR
    build_exe_dir = os.getenv("build_exe_dir")
    if not build_exe_dir:
        build_exe_dir = "build_exe"
    if not os.path.exists(build_exe_dir):
        os.makedirs(build_exe_dir)
    filepath = os.path.join(build_exe_dir, "_file_version_info.txt")
    ver1 = "0"; ver2 = "0"; ver3 = "0"; ver4 = "0"
    version_parts = app_version.split(".")
    if len(version_parts) > 0: ver1 = version_parts[0]
    if len(version_parts) > 1: ver2 = version_parts[1]
    if len(version_parts) > 2: ver2 = version_parts[2]
    if len(version_parts) > 3: ver4 = version_parts[3]
    substitutions = {}
    substitutions["ver1"] = ver1; substitutions["ver2"] = ver2; substitutions["ver3"] = ver3; substitutions["ver4"] = ver4
    substitutions["app_name"] = app_name
    substitutions["app_descr"] = app_descr
    substitutions["app_copyright"] = app_copyright
    version_info_file_txt = VERSION_FILE_INFO_TEMPLATE.format(**substitutions)
    f = None
    try:
        f = open(filepath, 'w')
    except Exception:
        err_str = 'Cannot write to file "' + filepath + '"\n'
    if f and not f.closed:
        f.write(version_info_file_txt)
        f.close()
    if err_str:
        retcode = 1
    return retcode, err_str

def substitute_in_file(filepath, substitutions_txt):
    # substitutions_txt is a comma-separated set of colon-separated key-value pairs to be converted to a dict
    # avoid comma and colon in either key or value
    retcode = 0
    err_str = ""
    f = None
    file_txt = ""
    substitutions = {}
    if substitutions_txt[0] == "{" and  substitutions_txt[-1] == "}":
        substitutions_txt = substitutions_txt[1:-1]
    print("-substitutions="+substitutions_txt)
    key_values = substitutions_txt.split(",")
    for key_value in key_values:
        key_value_pair = key_value.split(":")
        substitutions[key_value_pair[0]] = key_value_pair[1]
    try:
        f = open(filepath, 'r')
    except Exception:
        err_str = 'Cannot read file "' + filepath + '"\n'
    if f and not f.closed:
        file_txt = f.read()
        f.close()
    if not err_str:
        try:
            f = open(filepath, 'w')
        except Exception:
            err_str = 'Cannot write to file "' + filepath + '"\n'
        if f and not f.closed:
            #file_txt = file_txt.format(**substitutions) - confused by bash envvar substitutions (${...)
            for key, value in substitutions.items():
                file_txt = file_txt.replace('{'+key+'}', value)
            f.write(file_txt)
            f.close()
    if err_str:
        retcode = 1
    return retcode, err_str

if __name__ == "__main__":
    func_name = sys.argv[1]
    params = sys.argv[2:]  # Capture all subsequent arguments
    exit_code, result = globals()[func_name](*params)
    if result:
        print(result)
    exit(exit_code)
